name: VoLamV2
version: '1.0.0'
main: neo.volam2.main.Main
api-version: '1.21'
description: Vo Lam V2 - He Thong Mon Phai & Ky Nang
authors: [NeoTran]
depend: [MythicLib]
softdepend: [ParticleNativeAPI]

commands:
  kynang:
    description: Mo GUI ky nang
    usage: /kynang
  tiemnang:
    description: Mo GUI tiem nang
    usage: /tiemnang
  player:
    description: Mo GUI thong tin nhan vat
    usage: /player
    aliases: [nv, nhanvat]
  volam:
    description: Lenh admin VoLam
    usage: /volam admin <subcommand>
    permission: volam.admin
